Commit generated protobuf code, only regenerate on-demand
oll3/bita pull request #42
Opened 2024-04-04 13:13 UTC by MCOfficer

closes #41 

Since v0.11 (https://github.com/oll3/bita/commit/4fea65bc82e33acd18e2f48c7f4e52384c06c995), `prost-build` requires `protoc` to be installed while compiling. This means any downstream application / library of bitar also needs it to compile.

This PR adds the generated code directly the repository, and only regenerates it on-demand.

When to regenerate the code is a bit of a pain - you can't use `cargo:rerun-if-changed`, since that will run directly after a clean check-out. The best compromise between elegance and practicality i found was to only regenerate when the file was removed. I've added some comments to clarify this; since the file is edit rarely it shouldn't be that big of a hassle.

Alternative solutions to consider:

- use `rerun-if-changed` *and* check if `protoc` is in PATH. This "silent switch" could lead to build inconsistencies downstream, where the buildscript also runs.
- instead of shipping a `.rs` file, compile the protobuf files to a `.bin` using `protoc` and commit that. The buildscript would work as before (sourcing from the `.bin` instead of `.proto3`), without needing `protoc`. See for instance https://github.com/influxdata/pbjson/pull/79

2024-04-04 13:27 UTC, MCOfficer reviewed
Should also remove `protoc` from the CI, but i want to hear your thoughts first.

2024-04-04 20:17 UTC, oll3 requested changes
Looks good! Added a single request/question.

Other than that I think the method you've selected seems like the best option given the alternatives you listed. I think it makes it simple enough to regenerate the file when wanted.

> Should also remove protoc from the CI, but i want to hear your thoughts first.
The only reason I can think of to keep it would be to validate the checked-in file, but don't know what such a test would be good for really. Anyway, it can be restored if ever needed so let's remove it.

2024-04-05 05:27 UTC, oll3 commented on bitar/build.rs
> +    println!("cargo:rerun-if-changed=proto/"); // Note: change this to cargo:: (double colon) once MSRV>=1.77
> Anyways, I don't mind adding it or just dropping that line entirely. After all, it's only skipping the second check for whether the file exists.

True that, remove it then.

2024-04-05 10:12 UTC, merged

2024-04-05 10:13 UTC, oll3 commented
Thanks @MCOfficer !  :star: